sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t shekharkumar/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true shekharkumar/react-test npm test -- --coverage

after_success:
    - docker build -t shekharkumar/multi-client ./client
    - docker build -t shekharkumar/multi-nginx ./nginx
    - docker build -t shekharkumar/multi-server ./server
    - docker build -t shekharkumar/multi-worker ./worker
    #Log in to docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # take those images and push them to docker hub
    - docker push shekharkumar/multi-client
    - docker push shekharkumar/multi-nginx
    - docker push shekharkumar/multi-server
    - docker push shekharkumar/multi-worker